
bronze_sword = int(9)
silver_sword = int(10)
mythril_sword = int(14)
fists = int(6)
dagger = int(9)
rapier = int(11)
fists2 = int(11)
bronze_Dagger = int(7) 
silver_Dagger = int (10)
mythril_Dagger = int (13)
bronze_Pan = int(5)
silver_Pan = int(9)
mythril_Pan = int(12)
bronze_Hammer = int(8) 
silver_Hammer = int(10)
mythril_Hammer = int(13)

